# Generated by Django 4.0.2 on 2022-02-17 08:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for product', primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=200)),
                ('product_subcategory', models.CharField(max_length=200)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_buy_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['product_name', 'product_category', 'product_subcategory', 'product_brand'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('spec_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for specification', primary_key=True, serialize=False)),
                ('spec_name', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['spec_name'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('website_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for website', primary_key=True, serialize=False)),
                ('website_name', models.CharField(max_length=200)),
                ('website_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductWebsite',
            fields=[
                ('product_website_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for product-website relation', primary_key=True, serialize=False)),
                ('shipping_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('popularity_count', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_count', models.IntegerField(default=0)),
                ('image_path', models.CharField(max_length=200, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('website', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.website')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('product_spec_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for product specification relation', primary_key=True, serialize=False)),
                ('spec_val', models.CharField(default='', max_length=1000)),
                ('product_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productwebsite')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.specification')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for offer', primary_key=True, serialize=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_free_shipping', models.BooleanField(default=False)),
                ('buy_one_get_one_free', models.BooleanField(default=False)),
                ('product_website', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productwebsite')),
            ],
            options={
                'ordering': ['discount_percentage'],
            },
        ),
    ]
