# Generated by Django 4.0.2 on 2022-02-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-discount_percentage']},
        ),
        migrations.AlterModelOptions(
            name='productwebsite',
            options={},
        ),
        migrations.AddField(
            model_name='productwebsite',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=1000),
        ),
    ]
