# Generated by Django 4.0.2 on 2022-02-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_offer_options_alter_productwebsite_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productwebsite',
            options={'ordering': ['product_website_id']},
        ),
    ]
